=== hmcts/cpp-context-businessprocesses/businessprocesses-event/businessprocesses-event-processor/src/yaml/json/schema/public.progression.form-finalised.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://justice.gov.uk/core/courts/form-finalised.json",
  "type": "object",
  "properties": {
    "courtFormId": {
      "description": "Court Form Id",
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "caseId": {
      "description": "Case Id",
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "caseURN": {
      "description": "Case URN",
      "type": "string"
    },
    "formType": {
      "description": "Form Type",
      "type": "string",
      "enum": [
        "PET",
        "BCM",
        "PTPH"
      ]
    },
    "updatedBy": {
      "type": "object",
      "properties": {
        "id": {
          "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
        },
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "oneOf": [
        {
          "required": [
            "id",
            "firstName",
            "lastName"
          ]
        },
        {
          "required": [
            "name"
          ]
        }
      ]
    },
    "documentMetaData": {
      "description": "Array of meta data of all documents",
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "properties": {
          "isWelsh": {
            "type": "boolean"
          },
          "materialId": {
            "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
          },
          "fileName": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "submissionId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "hearingDateTime": {
      "type": "string",
      "format": "date-time"
    }
  },
  "required": [
    "caseId",
    "formType",
    "courtFormId",
    "updatedBy",
    "documentMetaData"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-businessprocesses/businessprocesses-event/businessprocesses-event-processor/src/test/resources/finalised-form-event-data.json
{
  "caseId": "%caseId%",
  "courtFormId": "%courtFormId%",
  "formType": "BCM",
  "hearingDateTime": "2025-12-22T10:45:00Z",
  "caseURN": "TFL4359536",
  "updatedBy": {
    "id": "%userId%",
    "firstName": "firstName",
    "lastName": "lastName"
  },
  "documentMetaData": [
    {
      "isWelsh": true,
      "materialId": "861922c8-28e6-4c73-866b-b80e270b1655",
      "fileName": "fileName One.pdf"
    },
    {
      "isWelsh": true,
      "materialId": "c0b6d9e0-5b89-4f7e-a457-894f17217486",
      "fileName": "fileName One.pdf"
    },
    {
      "isWelsh": true,
      "materialId": "37aa859a-6a13-4440-8ed9-489a668f8e7f",
      "fileName": "fileName One.pdf"
    }
  ]
}
