=== hmcts/cpp-context-businessprocesses/businessprocesses-event/businessprocesses-event-processor/src/yaml/json/schema/public.events.sjp.case-referred-to-court.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://cpp.moj.gov.uk/sjp/json/schema/event/public.events.sjp.case-referred-to-court.json",
  "type": "object",
  "properties": {
    "decisionId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "sessionId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "caseId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "urn": {
      "type": "string"
    },
    "defendantId": {
      "$ref": "http://justice.gov.uk/domain/core/common/definitions.json#/definitions/uuid"
    },
    "defendantName": {
      "type": "string"
    },
    "savedAt": {
      "$ref": "http://justice.gov.uk/json/schemas/domains/sjp/temporal.json#/definitions/date-time"
    },
    "offenceDecisions": {
      "$ref": "http://cpp.moj.gov.uk/core/sjp/decision/offenceDecisions.json"
    },
    "financialImposition": {
      "$ref": "http://cpp.moj.gov.uk/core/sjp/decision/financial-imposition/financialImposition.json"
    }
  },
  "required": [
    "decisionId",
    "sessionId",
    "caseId",
    "savedAt",
    "offenceDecisions"
  ],
  "additionalProperties": false
}

=== hmcts/cpp-context-businessprocesses/businessprocesses-integration-test/src/test/resources/sjpCaseDecisionSaved.json
{
  "decisionId": "11111111-1111-43e4-96c4-10fed16278ac",
  "sessionId": "87a321ef-ea34-47d7-865d-7f430b4775be",
  "caseId": "${CASE_ID}",
  "urn": "TFL34652354",
  "savedAt": "2019-05-01T15:12:30.741Z",
  "offenceDecisions": [
    {
      "offenceDecisionInformation": {
        "offenceId": "b0fb4f52-43c1-424b-976a-1dd4c9792cb0",
        "verdict": "NO_VERDICT",
        "pressRestrictable": true
      },
      "type": "WITHDRAW",
      "withdrawalReasonId": "030d4335-f9fe-39e0-ad7e-d01a0791ff87"
    },
    {
      "type" : "${TYPE}",
      "id" : "7305e600-334d-429a-bd34-bc76eeae4cfd",
      "offenceDecisionInformation" : [ {
        "offenceId" : "b0fb4f52-43c1-424b-976a-1dd4c9792cb1",
        "verdict" : "NO_VERDICT",
        "pressRestrictable" : false
      }, {
        "offenceId" : "cd7077ea-2d3f-4f37-b16e-e1dfea7c4a59",
        "verdict" : "NO_VERDICT",
        "pressRestrictable" : false
      } ],
      "referralReasonId" : "9753b66a-8845-491f-a42b-7fc207ae6b1b",
      "referralReason" : "For a case management hearing (Defendant to attend)",
      "estimatedHearingDuration" : 20,
      "defendantCourtOptions" : {
        "interpreter" : {
          "language" : "Mirpuri",
          "needed" : true
        },
        "welshHearing" : false,
        "disabilityNeeds" : {
          "needed" : false
        }
      },
      "nextHearing" : {
        "courtCentre" : {
          "id" : "3b9a61dd-d484-3ee7-a0b8-5954aea415bc",
          "name" : "Bradford Magistrates' Court",
          "roomId" : "a93c8edb-0429-3d3e-85f5-b186a9f1f3e3"
        },
        "estimatedMinutes" : 20,
        "listedStartDateTime" : "2024-08-22T13:00:00.000Z",
        "type" : {
          "description" : "Pre-Trial Review",
          "id" : "c6d76309-c912-436b-a21b-a4c4450bc052"
        }
      }
    }
  ],
  "defendantId":"1a71d4b1-e0e1-4685-beb7-97e33fb2e799" ,
  "defendantName": "Abbie ARMSTRONG"
}

=== hmcts/cpp-context-businessprocesses/businessprocesses-event/businessprocesses-event-processor/src/yaml/json/public.events.sjp.case-referred-to-court.json
{
  "decisionId": "fc3f8d82-d200-4cab-a492-2796e6fdf42c",
  "sessionId": "87a321ef-ea34-47d7-865d-7f430b4775be",
  "caseId": "0a71d4b1-e0e1-4685-beb7-97e33fb2e799",
  "urn": "TFL34652354",
  "savedAt": "2019-05-01T15:12:30.741Z",
  "offenceDecisions": [
    {
      "offenceDecisionInformation": {
        "offenceId": "b0fb4f52-43c1-424b-976a-1dd4c9792cb0",
        "verdict": "NO_VERDICT",
        "pressRestrictable": true
      },
      "type": "REFER_FOR_COURT_HEARING",
      "withdrawalReasonId": "030d4335-f9fe-39e0-ad7e-d01a0791ff87",
      "nextHearing": {
        "type": {
          "description": "Trial",
          "id": "bf8155e1-90b9-4080-b133-bfbad895d6e4"
        },
        "courtCentre": {
          "id": "4b6185e1-92f2-3634-b749-87d2fcadf1c8",
          "name": "Basingstoke Magistrates' Court",
          "roomId": "5c432fcf-ba6c-47ad-8c46-dd717106bf4d"
        },
        "estimatedMinutes": 20,
        "listedStartDateTime": "2023-10-12T10:10:09.123Z"
      }
    },
    {
      "offenceDecisionInformation": {
        "offenceId": "b0fb4f52-43c1-424b-976a-1dd4c9792cb1",
        "verdict": "NO_VERDICT",
        "pressRestrictable": false
      },
      "type": "WITHDRAW",
      "withdrawalReasonId": "030d4335-f9fe-39e0-ad7e-d01a0791ff87"
    }
  ],
  "defendantId":"1a71d4b1-e0e1-4685-beb7-97e33fb2e799" ,
  "defendantName": "Abbie ARMSTRONG"
}

=== hmcts/cpp-context-businessprocesses/businessprocesses-event/businessprocesses-event-processor/src/test/resources/sjpCaseDecisionSaved.json
{
  "decisionId": "11111111-1111-43e4-96c4-10fed16278ac",
  "sessionId": "87a321ef-ea34-47d7-865d-7f430b4775be",
  "caseId": "${CASE_ID}",
  "urn": "TFL34652354",
  "savedAt": "2019-05-01T15:12:30.741Z",
  "offenceDecisions": [
    {
      "offenceDecisionInformation": {
        "offenceId": "b0fb4f52-43c1-424b-976a-1dd4c9792cb0",
        "verdict": "NO_VERDICT",
        "pressRestrictable": true
      },
      "type": "WITHDRAW",
      "withdrawalReasonId": "030d4335-f9fe-39e0-ad7e-d01a0791ff87"
    },
    {
      "offenceDecisionInformation": {
        "offenceId": "b0fb4f52-43c1-424b-976a-1dd4c9792cb1",
        "verdict": "NO_VERDICT",
        "pressRestrictable": false
      },
      "type": "${TYPE}",
      "withdrawalReasonId": "030d4335-f9fe-39e0-ad7e-d01a0791ff87",
      "nextHearing": {
        "type": {
          "description": "Trial",
          "id": "bf8155e1-90b9-4080-b133-bfbad895d6e4"
        },
        "courtCentre": {
          "id": "4b6185e1-92f2-3634-b749-87d2fcadf1c8",
          "name": "Basingstoke Magistrates' Court",
          "roomId": "5c432fcf-ba6c-47ad-8c46-dd717106bf4d"
        },
        "estimatedMinutes": 20,
        "listedStartDateTime": "2023-10-12T10:10:09.123Z"
      }
    }
  ],
  "defendantId":"1a71d4b1-e0e1-4685-beb7-97e33fb2e799" ,
  "defendantName": "Abbie ARMSTRONG"
}
